spring:
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/devpub}
    username: root
    password: testtest
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 10MB
  mail:
    host: smtp.mail.ru
    port: 465
    protocol: smtps
    username: loginov-mikhail@mail.ru
    password: EtVmqH6lOo5NUESCt80W
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

server:
  port: ${PORT:8080}

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 922 669-63-95
  email: paytonklon@gmail.com
  copyright: Mike Loginov
  copyrightfrom: 2021