spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: true
spring.datasource.url: jdbc:mysql://localhost:3306/devpub
spring.datasource.username: root
spring.datasource.password: testtest

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 922 669-63-95
blog.email: paytonklon@gmail.com
blog.copyright: Mike Loginov
blog.copyrightfrom: 2021