spring:
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/devpub
    username: root
    password: testtest
  mail:
    host: smtp.mail.ru
    port: 465
    protocol: smtps
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true


blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 922 669-63-95
  email: paytonklon@gmail.com
  copyright: Mike Loginov
  copyrightfrom: 2021